server:
  servlet:
    context-path: /kbms
  port: 8080

user:
   id: 1
   name: 习大大
   age: 21
   adrress: 湖南
   sex: 男
   description: 这是个傻逼
name: 高吧
age : 123
spring:
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false
  aop:
    proxy-target-class: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kbms?serverTimezone=GMT%2B8&useunicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      current_session_context_class : org.springframework.orm.hibernate4.SpringSessionContext
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  jackson:
    date-format: yyyy年MM月dd天HH:mm:ss
    time-zone: GMT+8




debug:
  true
